### ISSUE TITLE
关于测试图的问题

### ISSUE THREAD

**Issue by Lininggggggg** [zhaohengyuan1/PAN#4]
您好，请问能提供论文图5中各个模型的结果图吗？或者这些应该是在哪里能找到呢？还是说都是需要自己去复现每一篇论文的结果呢？
我想引用对比您们的结果，但不清楚这些经典模型的效果图需要怎么得到？能告诉我下吗？谢谢

**Comment by zhaohengyuan1** [comment]
这个链接可以下载测试图https://drive.google.com/drive/folders/1lsoyAjsUEyp7gm1t6vZI9j7jr9YzKzcF?usp=sharing，然后用readme里面的代码可以跑测试结果。

**Comment by zhaohengyuan1** [comment]
这个是PAN的实验结果的地址百度云盘的地址
链接:https://pan.baidu.com/s/1ZsM-RUoPVor-7vWknK6jlg  密码:ujpf

**Comment by Luyingxing** [comment]
您好，PAN的实验结果的百度网盘地址已过期，请问可以发一下地址吗？

**Comment by zhaohengyuan1** [comment]
您好，感谢您对PAN的关注，前段时间忙MM的DDL，所以没来得及回复消息，results的地址为链接:
https://pan.baidu.com/s/15xAwojWF1AAyGiSsqgeDsA  密码: a4k3。
感谢~

Luyingxing ***@***.***> 于2021年4月11日周日 下午4:32写道：

**Comment by zhaohengyuan1** [comment]
您好，我存放results结果的地址，被百度网盘认为有害，现在不能分享，google drive可以使用，您也可以下载model按照github
的指引自行测试。
感谢~

Luyingxing ***@***.***> 于2021年4月11日周日 下午4:32写道：

**Comment by Lininggggggg** [comment]
好的，谢谢哈
